// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// B2CAPIClient is the client API for B2CAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type B2CAPIClient interface {
	// Transfer funds from business to customer or another business
	TransferFunds(ctx context.Context, in *TransferFundsRequest, opts ...grpc.CallOption) (*TransferFundsResponse, error)
	// Queries for query transaction
	QueryTransactionStatus(ctx context.Context, in *QueryTransactionStatusRequest, opts ...grpc.CallOption) (*QueryResponse, error)
	// Queries for account balance
	QueryAccountBalance(ctx context.Context, in *QueryAccountBalanceRequest, opts ...grpc.CallOption) (*QueryAccountBalanceResponse, error)
	// Reverses an mpesa transaction
	ReverseTransaction(ctx context.Context, in *ReverseTransactionRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Creates a record of b2c payment
	CreateB2CPayment(ctx context.Context, in *CreateB2CPaymentRequest, opts ...grpc.CallOption) (*B2CPayment, error)
	// Retrieves a single b2c payment
	GetB2CPayment(ctx context.Context, in *GetB2CPaymentRequest, opts ...grpc.CallOption) (*B2CPayment, error)
	// Retrieves a collection of b2c payments
	ListB2CPayments(ctx context.Context, in *ListB2CPaymentsRequest, opts ...grpc.CallOption) (*ListB2CPaymentsResponse, error)
	// Processes b2c payment updating its status
	ProcessB2CPayment(ctx context.Context, in *ProcessB2CPaymentRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Publishes b2c payment to consumers
	PublishB2CPayment(ctx context.Context, in *PublishB2CPaymentRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Retrieves a collection of statistics
	ListDailyStats(ctx context.Context, in *ListDailyStatsRequest, opts ...grpc.CallOption) (*StatsResponse, error)
}

type b2CAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewB2CAPIClient(cc grpc.ClientConnInterface) B2CAPIClient {
	return &b2CAPIClient{cc}
}

func (c *b2CAPIClient) TransferFunds(ctx context.Context, in *TransferFundsRequest, opts ...grpc.CallOption) (*TransferFundsResponse, error) {
	out := new(TransferFundsResponse)
	err := c.cc.Invoke(ctx, "/gidyon.mpesa.b2c.B2CAPI/TransferFunds", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *b2CAPIClient) QueryTransactionStatus(ctx context.Context, in *QueryTransactionStatusRequest, opts ...grpc.CallOption) (*QueryResponse, error) {
	out := new(QueryResponse)
	err := c.cc.Invoke(ctx, "/gidyon.mpesa.b2c.B2CAPI/QueryTransactionStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *b2CAPIClient) QueryAccountBalance(ctx context.Context, in *QueryAccountBalanceRequest, opts ...grpc.CallOption) (*QueryAccountBalanceResponse, error) {
	out := new(QueryAccountBalanceResponse)
	err := c.cc.Invoke(ctx, "/gidyon.mpesa.b2c.B2CAPI/QueryAccountBalance", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *b2CAPIClient) ReverseTransaction(ctx context.Context, in *ReverseTransactionRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/gidyon.mpesa.b2c.B2CAPI/ReverseTransaction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *b2CAPIClient) CreateB2CPayment(ctx context.Context, in *CreateB2CPaymentRequest, opts ...grpc.CallOption) (*B2CPayment, error) {
	out := new(B2CPayment)
	err := c.cc.Invoke(ctx, "/gidyon.mpesa.b2c.B2CAPI/CreateB2CPayment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *b2CAPIClient) GetB2CPayment(ctx context.Context, in *GetB2CPaymentRequest, opts ...grpc.CallOption) (*B2CPayment, error) {
	out := new(B2CPayment)
	err := c.cc.Invoke(ctx, "/gidyon.mpesa.b2c.B2CAPI/GetB2CPayment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *b2CAPIClient) ListB2CPayments(ctx context.Context, in *ListB2CPaymentsRequest, opts ...grpc.CallOption) (*ListB2CPaymentsResponse, error) {
	out := new(ListB2CPaymentsResponse)
	err := c.cc.Invoke(ctx, "/gidyon.mpesa.b2c.B2CAPI/ListB2CPayments", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *b2CAPIClient) ProcessB2CPayment(ctx context.Context, in *ProcessB2CPaymentRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/gidyon.mpesa.b2c.B2CAPI/ProcessB2CPayment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *b2CAPIClient) PublishB2CPayment(ctx context.Context, in *PublishB2CPaymentRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/gidyon.mpesa.b2c.B2CAPI/PublishB2CPayment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *b2CAPIClient) ListDailyStats(ctx context.Context, in *ListDailyStatsRequest, opts ...grpc.CallOption) (*StatsResponse, error) {
	out := new(StatsResponse)
	err := c.cc.Invoke(ctx, "/gidyon.mpesa.b2c.B2CAPI/ListDailyStats", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// B2CAPIServer is the server API for B2CAPI service.
// All implementations must embed UnimplementedB2CAPIServer
// for forward compatibility
type B2CAPIServer interface {
	// Transfer funds from business to customer or another business
	TransferFunds(context.Context, *TransferFundsRequest) (*TransferFundsResponse, error)
	// Queries for query transaction
	QueryTransactionStatus(context.Context, *QueryTransactionStatusRequest) (*QueryResponse, error)
	// Queries for account balance
	QueryAccountBalance(context.Context, *QueryAccountBalanceRequest) (*QueryAccountBalanceResponse, error)
	// Reverses an mpesa transaction
	ReverseTransaction(context.Context, *ReverseTransactionRequest) (*emptypb.Empty, error)
	// Creates a record of b2c payment
	CreateB2CPayment(context.Context, *CreateB2CPaymentRequest) (*B2CPayment, error)
	// Retrieves a single b2c payment
	GetB2CPayment(context.Context, *GetB2CPaymentRequest) (*B2CPayment, error)
	// Retrieves a collection of b2c payments
	ListB2CPayments(context.Context, *ListB2CPaymentsRequest) (*ListB2CPaymentsResponse, error)
	// Processes b2c payment updating its status
	ProcessB2CPayment(context.Context, *ProcessB2CPaymentRequest) (*emptypb.Empty, error)
	// Publishes b2c payment to consumers
	PublishB2CPayment(context.Context, *PublishB2CPaymentRequest) (*emptypb.Empty, error)
	// Retrieves a collection of statistics
	ListDailyStats(context.Context, *ListDailyStatsRequest) (*StatsResponse, error)
	mustEmbedUnimplementedB2CAPIServer()
}

// UnimplementedB2CAPIServer must be embedded to have forward compatible implementations.
type UnimplementedB2CAPIServer struct {
}

func (UnimplementedB2CAPIServer) TransferFunds(context.Context, *TransferFundsRequest) (*TransferFundsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TransferFunds not implemented")
}
func (UnimplementedB2CAPIServer) QueryTransactionStatus(context.Context, *QueryTransactionStatusRequest) (*QueryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryTransactionStatus not implemented")
}
func (UnimplementedB2CAPIServer) QueryAccountBalance(context.Context, *QueryAccountBalanceRequest) (*QueryAccountBalanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryAccountBalance not implemented")
}
func (UnimplementedB2CAPIServer) ReverseTransaction(context.Context, *ReverseTransactionRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReverseTransaction not implemented")
}
func (UnimplementedB2CAPIServer) CreateB2CPayment(context.Context, *CreateB2CPaymentRequest) (*B2CPayment, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateB2CPayment not implemented")
}
func (UnimplementedB2CAPIServer) GetB2CPayment(context.Context, *GetB2CPaymentRequest) (*B2CPayment, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetB2CPayment not implemented")
}
func (UnimplementedB2CAPIServer) ListB2CPayments(context.Context, *ListB2CPaymentsRequest) (*ListB2CPaymentsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListB2CPayments not implemented")
}
func (UnimplementedB2CAPIServer) ProcessB2CPayment(context.Context, *ProcessB2CPaymentRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProcessB2CPayment not implemented")
}
func (UnimplementedB2CAPIServer) PublishB2CPayment(context.Context, *PublishB2CPaymentRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PublishB2CPayment not implemented")
}
func (UnimplementedB2CAPIServer) ListDailyStats(context.Context, *ListDailyStatsRequest) (*StatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListDailyStats not implemented")
}
func (UnimplementedB2CAPIServer) mustEmbedUnimplementedB2CAPIServer() {}

// UnsafeB2CAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to B2CAPIServer will
// result in compilation errors.
type UnsafeB2CAPIServer interface {
	mustEmbedUnimplementedB2CAPIServer()
}

func RegisterB2CAPIServer(s grpc.ServiceRegistrar, srv B2CAPIServer) {
	s.RegisterService(&_B2CAPI_serviceDesc, srv)
}

func _B2CAPI_TransferFunds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransferFundsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(B2CAPIServer).TransferFunds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gidyon.mpesa.b2c.B2CAPI/TransferFunds",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(B2CAPIServer).TransferFunds(ctx, req.(*TransferFundsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _B2CAPI_QueryTransactionStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryTransactionStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(B2CAPIServer).QueryTransactionStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gidyon.mpesa.b2c.B2CAPI/QueryTransactionStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(B2CAPIServer).QueryTransactionStatus(ctx, req.(*QueryTransactionStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _B2CAPI_QueryAccountBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAccountBalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(B2CAPIServer).QueryAccountBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gidyon.mpesa.b2c.B2CAPI/QueryAccountBalance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(B2CAPIServer).QueryAccountBalance(ctx, req.(*QueryAccountBalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _B2CAPI_ReverseTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReverseTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(B2CAPIServer).ReverseTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gidyon.mpesa.b2c.B2CAPI/ReverseTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(B2CAPIServer).ReverseTransaction(ctx, req.(*ReverseTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _B2CAPI_CreateB2CPayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateB2CPaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(B2CAPIServer).CreateB2CPayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gidyon.mpesa.b2c.B2CAPI/CreateB2CPayment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(B2CAPIServer).CreateB2CPayment(ctx, req.(*CreateB2CPaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _B2CAPI_GetB2CPayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetB2CPaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(B2CAPIServer).GetB2CPayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gidyon.mpesa.b2c.B2CAPI/GetB2CPayment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(B2CAPIServer).GetB2CPayment(ctx, req.(*GetB2CPaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _B2CAPI_ListB2CPayments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListB2CPaymentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(B2CAPIServer).ListB2CPayments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gidyon.mpesa.b2c.B2CAPI/ListB2CPayments",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(B2CAPIServer).ListB2CPayments(ctx, req.(*ListB2CPaymentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _B2CAPI_ProcessB2CPayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProcessB2CPaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(B2CAPIServer).ProcessB2CPayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gidyon.mpesa.b2c.B2CAPI/ProcessB2CPayment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(B2CAPIServer).ProcessB2CPayment(ctx, req.(*ProcessB2CPaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _B2CAPI_PublishB2CPayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishB2CPaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(B2CAPIServer).PublishB2CPayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gidyon.mpesa.b2c.B2CAPI/PublishB2CPayment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(B2CAPIServer).PublishB2CPayment(ctx, req.(*PublishB2CPaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _B2CAPI_ListDailyStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDailyStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(B2CAPIServer).ListDailyStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gidyon.mpesa.b2c.B2CAPI/ListDailyStats",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(B2CAPIServer).ListDailyStats(ctx, req.(*ListDailyStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _B2CAPI_serviceDesc = grpc.ServiceDesc{
	ServiceName: "gidyon.mpesa.b2c.B2CAPI",
	HandlerType: (*B2CAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TransferFunds",
			Handler:    _B2CAPI_TransferFunds_Handler,
		},
		{
			MethodName: "QueryTransactionStatus",
			Handler:    _B2CAPI_QueryTransactionStatus_Handler,
		},
		{
			MethodName: "QueryAccountBalance",
			Handler:    _B2CAPI_QueryAccountBalance_Handler,
		},
		{
			MethodName: "ReverseTransaction",
			Handler:    _B2CAPI_ReverseTransaction_Handler,
		},
		{
			MethodName: "CreateB2CPayment",
			Handler:    _B2CAPI_CreateB2CPayment_Handler,
		},
		{
			MethodName: "GetB2CPayment",
			Handler:    _B2CAPI_GetB2CPayment_Handler,
		},
		{
			MethodName: "ListB2CPayments",
			Handler:    _B2CAPI_ListB2CPayments_Handler,
		},
		{
			MethodName: "ProcessB2CPayment",
			Handler:    _B2CAPI_ProcessB2CPayment_Handler,
		},
		{
			MethodName: "PublishB2CPayment",
			Handler:    _B2CAPI_PublishB2CPayment_Handler,
		},
		{
			MethodName: "ListDailyStats",
			Handler:    _B2CAPI_ListDailyStats_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "b2c.v1.proto",
}
