// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UnsafeLipaNaMPESAServer is an autogenerated mock type for the UnsafeLipaNaMPESAServer type
type UnsafeLipaNaMPESAServer struct {
	mock.Mock
}

// mustEmbedUnimplementedLipaNaMPESAServer provides a mock function with given fields:
func (_m *UnsafeLipaNaMPESAServer) mustEmbedUnimplementedLipaNaMPESAServer() {
	_m.Called()
}
