// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UnsafeB2CAPIServer is an autogenerated mock type for the UnsafeB2CAPIServer type
type UnsafeB2CAPIServer struct {
	mock.Mock
}

// mustEmbedUnimplementedB2CAPIServer provides a mock function with given fields:
func (_m *UnsafeB2CAPIServer) mustEmbedUnimplementedB2CAPIServer() {
	_m.Called()
}
