// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UnsafeStkPushAPIServer is an autogenerated mock type for the UnsafeStkPushAPIServer type
type UnsafeStkPushAPIServer struct {
	mock.Mock
}

// mustEmbedUnimplementedStkPushAPIServer provides a mock function with given fields:
func (_m *UnsafeStkPushAPIServer) mustEmbedUnimplementedStkPushAPIServer() {
	_m.Called()
}
