// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v2

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// B2CV2Client is the client API for B2CV2 service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type B2CV2Client interface {
	// Transfer funds from business to customer or another business
	TransferFunds(ctx context.Context, in *TransferFundsRequest, opts ...grpc.CallOption) (*TransferFundsResponse, error)
	// Retrieves a single b2c payment
	GetB2CPayment(ctx context.Context, in *GetB2CPaymentRequest, opts ...grpc.CallOption) (*B2CPayment, error)
	// Retrieves a collection of b2c payments
	ListB2CPayments(ctx context.Context, in *ListB2CPaymentsRequest, opts ...grpc.CallOption) (*ListB2CPaymentsResponse, error)
	// Processes b2c payment updating its status
	ProcessB2CPayment(ctx context.Context, in *ProcessB2CPaymentRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Publishes b2c payment to consumers
	PublishB2CPayment(ctx context.Context, in *PublishB2CPaymentRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Retrieves a collection of statistics
	ListDailyStats(ctx context.Context, in *ListDailyStatsRequest, opts ...grpc.CallOption) (*StatsResponse, error)
	// Queries for query transaction
	QueryTransactionStatus(ctx context.Context, in *QueryTransactionStatusRequest, opts ...grpc.CallOption) (*QueryResponse, error)
	// Queries for account balance
	QueryAccountBalance(ctx context.Context, in *QueryAccountBalanceRequest, opts ...grpc.CallOption) (*QueryAccountBalanceResponse, error)
	// Reverses an mpesa transaction
	ReverseTransaction(ctx context.Context, in *ReverseTransactionRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type b2CV2Client struct {
	cc grpc.ClientConnInterface
}

func NewB2CV2Client(cc grpc.ClientConnInterface) B2CV2Client {
	return &b2CV2Client{cc}
}

func (c *b2CV2Client) TransferFunds(ctx context.Context, in *TransferFundsRequest, opts ...grpc.CallOption) (*TransferFundsResponse, error) {
	out := new(TransferFundsResponse)
	err := c.cc.Invoke(ctx, "/gidyon.mpesa.b2c.B2CV2/TransferFunds", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *b2CV2Client) GetB2CPayment(ctx context.Context, in *GetB2CPaymentRequest, opts ...grpc.CallOption) (*B2CPayment, error) {
	out := new(B2CPayment)
	err := c.cc.Invoke(ctx, "/gidyon.mpesa.b2c.B2CV2/GetB2CPayment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *b2CV2Client) ListB2CPayments(ctx context.Context, in *ListB2CPaymentsRequest, opts ...grpc.CallOption) (*ListB2CPaymentsResponse, error) {
	out := new(ListB2CPaymentsResponse)
	err := c.cc.Invoke(ctx, "/gidyon.mpesa.b2c.B2CV2/ListB2CPayments", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *b2CV2Client) ProcessB2CPayment(ctx context.Context, in *ProcessB2CPaymentRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/gidyon.mpesa.b2c.B2CV2/ProcessB2CPayment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *b2CV2Client) PublishB2CPayment(ctx context.Context, in *PublishB2CPaymentRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/gidyon.mpesa.b2c.B2CV2/PublishB2CPayment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *b2CV2Client) ListDailyStats(ctx context.Context, in *ListDailyStatsRequest, opts ...grpc.CallOption) (*StatsResponse, error) {
	out := new(StatsResponse)
	err := c.cc.Invoke(ctx, "/gidyon.mpesa.b2c.B2CV2/ListDailyStats", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *b2CV2Client) QueryTransactionStatus(ctx context.Context, in *QueryTransactionStatusRequest, opts ...grpc.CallOption) (*QueryResponse, error) {
	out := new(QueryResponse)
	err := c.cc.Invoke(ctx, "/gidyon.mpesa.b2c.B2CV2/QueryTransactionStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *b2CV2Client) QueryAccountBalance(ctx context.Context, in *QueryAccountBalanceRequest, opts ...grpc.CallOption) (*QueryAccountBalanceResponse, error) {
	out := new(QueryAccountBalanceResponse)
	err := c.cc.Invoke(ctx, "/gidyon.mpesa.b2c.B2CV2/QueryAccountBalance", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *b2CV2Client) ReverseTransaction(ctx context.Context, in *ReverseTransactionRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/gidyon.mpesa.b2c.B2CV2/ReverseTransaction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// B2CV2Server is the server API for B2CV2 service.
// All implementations must embed UnimplementedB2CV2Server
// for forward compatibility
type B2CV2Server interface {
	// Transfer funds from business to customer or another business
	TransferFunds(context.Context, *TransferFundsRequest) (*TransferFundsResponse, error)
	// Retrieves a single b2c payment
	GetB2CPayment(context.Context, *GetB2CPaymentRequest) (*B2CPayment, error)
	// Retrieves a collection of b2c payments
	ListB2CPayments(context.Context, *ListB2CPaymentsRequest) (*ListB2CPaymentsResponse, error)
	// Processes b2c payment updating its status
	ProcessB2CPayment(context.Context, *ProcessB2CPaymentRequest) (*emptypb.Empty, error)
	// Publishes b2c payment to consumers
	PublishB2CPayment(context.Context, *PublishB2CPaymentRequest) (*emptypb.Empty, error)
	// Retrieves a collection of statistics
	ListDailyStats(context.Context, *ListDailyStatsRequest) (*StatsResponse, error)
	// Queries for query transaction
	QueryTransactionStatus(context.Context, *QueryTransactionStatusRequest) (*QueryResponse, error)
	// Queries for account balance
	QueryAccountBalance(context.Context, *QueryAccountBalanceRequest) (*QueryAccountBalanceResponse, error)
	// Reverses an mpesa transaction
	ReverseTransaction(context.Context, *ReverseTransactionRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedB2CV2Server()
}

// UnimplementedB2CV2Server must be embedded to have forward compatible implementations.
type UnimplementedB2CV2Server struct {
}

func (UnimplementedB2CV2Server) TransferFunds(context.Context, *TransferFundsRequest) (*TransferFundsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TransferFunds not implemented")
}
func (UnimplementedB2CV2Server) GetB2CPayment(context.Context, *GetB2CPaymentRequest) (*B2CPayment, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetB2CPayment not implemented")
}
func (UnimplementedB2CV2Server) ListB2CPayments(context.Context, *ListB2CPaymentsRequest) (*ListB2CPaymentsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListB2CPayments not implemented")
}
func (UnimplementedB2CV2Server) ProcessB2CPayment(context.Context, *ProcessB2CPaymentRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProcessB2CPayment not implemented")
}
func (UnimplementedB2CV2Server) PublishB2CPayment(context.Context, *PublishB2CPaymentRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PublishB2CPayment not implemented")
}
func (UnimplementedB2CV2Server) ListDailyStats(context.Context, *ListDailyStatsRequest) (*StatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListDailyStats not implemented")
}
func (UnimplementedB2CV2Server) QueryTransactionStatus(context.Context, *QueryTransactionStatusRequest) (*QueryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryTransactionStatus not implemented")
}
func (UnimplementedB2CV2Server) QueryAccountBalance(context.Context, *QueryAccountBalanceRequest) (*QueryAccountBalanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryAccountBalance not implemented")
}
func (UnimplementedB2CV2Server) ReverseTransaction(context.Context, *ReverseTransactionRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReverseTransaction not implemented")
}
func (UnimplementedB2CV2Server) mustEmbedUnimplementedB2CV2Server() {}

// UnsafeB2CV2Server may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to B2CV2Server will
// result in compilation errors.
type UnsafeB2CV2Server interface {
	mustEmbedUnimplementedB2CV2Server()
}

func RegisterB2CV2Server(s grpc.ServiceRegistrar, srv B2CV2Server) {
	s.RegisterService(&_B2CV2_serviceDesc, srv)
}

func _B2CV2_TransferFunds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransferFundsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(B2CV2Server).TransferFunds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gidyon.mpesa.b2c.B2CV2/TransferFunds",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(B2CV2Server).TransferFunds(ctx, req.(*TransferFundsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _B2CV2_GetB2CPayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetB2CPaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(B2CV2Server).GetB2CPayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gidyon.mpesa.b2c.B2CV2/GetB2CPayment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(B2CV2Server).GetB2CPayment(ctx, req.(*GetB2CPaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _B2CV2_ListB2CPayments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListB2CPaymentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(B2CV2Server).ListB2CPayments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gidyon.mpesa.b2c.B2CV2/ListB2CPayments",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(B2CV2Server).ListB2CPayments(ctx, req.(*ListB2CPaymentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _B2CV2_ProcessB2CPayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProcessB2CPaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(B2CV2Server).ProcessB2CPayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gidyon.mpesa.b2c.B2CV2/ProcessB2CPayment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(B2CV2Server).ProcessB2CPayment(ctx, req.(*ProcessB2CPaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _B2CV2_PublishB2CPayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishB2CPaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(B2CV2Server).PublishB2CPayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gidyon.mpesa.b2c.B2CV2/PublishB2CPayment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(B2CV2Server).PublishB2CPayment(ctx, req.(*PublishB2CPaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _B2CV2_ListDailyStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDailyStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(B2CV2Server).ListDailyStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gidyon.mpesa.b2c.B2CV2/ListDailyStats",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(B2CV2Server).ListDailyStats(ctx, req.(*ListDailyStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _B2CV2_QueryTransactionStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryTransactionStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(B2CV2Server).QueryTransactionStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gidyon.mpesa.b2c.B2CV2/QueryTransactionStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(B2CV2Server).QueryTransactionStatus(ctx, req.(*QueryTransactionStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _B2CV2_QueryAccountBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAccountBalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(B2CV2Server).QueryAccountBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gidyon.mpesa.b2c.B2CV2/QueryAccountBalance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(B2CV2Server).QueryAccountBalance(ctx, req.(*QueryAccountBalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _B2CV2_ReverseTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReverseTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(B2CV2Server).ReverseTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gidyon.mpesa.b2c.B2CV2/ReverseTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(B2CV2Server).ReverseTransaction(ctx, req.(*ReverseTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _B2CV2_serviceDesc = grpc.ServiceDesc{
	ServiceName: "gidyon.mpesa.b2c.B2CV2",
	HandlerType: (*B2CV2Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TransferFunds",
			Handler:    _B2CV2_TransferFunds_Handler,
		},
		{
			MethodName: "GetB2CPayment",
			Handler:    _B2CV2_GetB2CPayment_Handler,
		},
		{
			MethodName: "ListB2CPayments",
			Handler:    _B2CV2_ListB2CPayments_Handler,
		},
		{
			MethodName: "ProcessB2CPayment",
			Handler:    _B2CV2_ProcessB2CPayment_Handler,
		},
		{
			MethodName: "PublishB2CPayment",
			Handler:    _B2CV2_PublishB2CPayment_Handler,
		},
		{
			MethodName: "ListDailyStats",
			Handler:    _B2CV2_ListDailyStats_Handler,
		},
		{
			MethodName: "QueryTransactionStatus",
			Handler:    _B2CV2_QueryTransactionStatus_Handler,
		},
		{
			MethodName: "QueryAccountBalance",
			Handler:    _B2CV2_QueryAccountBalance_Handler,
		},
		{
			MethodName: "ReverseTransaction",
			Handler:    _B2CV2_ReverseTransaction_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "b2c.v2.proto",
}
