apiVersion: v1
kind: ConfigMap
metadata:
  name: mpesapayment
  namespace: crbt
  labels:
    app: mpesapayment
data:
  config.yml: |
    serviceName: "MPESA Payments API"
    httpPort: 80
    startupSleepSeconds: 10
    logLevel: -1
    security:
      insecure: true
    databases:
    - required: true
      type: sqlDatabase
      address: mysql.databases:3306
      user: root
      schema: trackingportal
      passwordFile: /app/secrets/mysql/mysql-root-password
      metadata:
        name: sqlWrites
        dialect: mysql
        orm: gorm
    - required: true
      type: redisDatabase
      address: redis-master.databases:6379
      passwordFile: /app/secrets/redis/redis-root-password
      metadata:
        name: redisWrites
---
apiVersion: v1
kind: Service
metadata:
  name: mpesapayment
  namespace: crbt
  labels:
    app: mpesapayment
spec:
  selector:
    app: mpesapayment
  ports:
  - port: 80
    name: http
  - port: 8080
    name: grpc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mpesapayment
  namespace: crbt
  labels:
    app: mpesapayment
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mpesapayment
      version: v1
  template:
    metadata:
      labels:
        app: mpesapayment
        version: v1
    spec:
      containers:
      - name: mpesapayment
        image: gidyon/mpesapayment:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        - containerPort: 8080
          name: grpc
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 15Mi
          limits:
            cpu: 1000m
            memory: 200Mi
        env:
        - name: MPESA_ACCOUNT_REFERENCE
          value: Portal Paybill
        - name: MPESA_ACCESS_TOKEN_URL
          value: "https://sandbox.safaricom.co.ke/oauth/v1/generate?grant_type=client_credentials"
        - name: MPESA_POST_URL
          value: "https://sandbox.safaricom.co.ke/mpesa/stkpush/v1/processrequest"
        - name: MPESA_QUERY_URL
          value: "https://sandbox.safaricom.co.ke/mpesa/stkpushquery/v1/query"
        - name: MPESA_CALLBACK_URL
          value: "https://onfon.gidyon.jessegitaka.org/api/mpesapayment/incoming/stkpush"
        - name: MPESA_ACCESS_TOKEN
          valueFrom:
              secretKeyRef:
                name: mpesa-creds
                key: access-token
        - name: MPESA_ACCESS_TIMESTAMP
          valueFrom:
              secretKeyRef:
                name: mpesa-creds
                key: access-timestamp
        - name: MPESA_ACCESS_PASSWORD
          valueFrom:
              secretKeyRef:
                name: mpesa-creds
                key: access-password
        - name: SAF_CONSUMER_KEY
          valueFrom:
              secretKeyRef:
                name: mpesa-creds
                key: consumer-key
        - name: SAF_CONSUMER_SECRET
          valueFrom:
              secretKeyRef:
                name: mpesa-creds
                key: consumer-secret
        - name: BUSINESS_SHORT_CODE
          valueFrom:
              secretKeyRef:
                name: mpesa-creds
                key: business-short-code
        - name: API_HASH_KEY
          valueFrom:
            secretKeyRef:
              name: symmetric-keys
              key: api-hash-key
        - name: API_BLOCK_KEY
          valueFrom:
            secretKeyRef:
              name: symmetric-keys
              key: api-block-key
        - name: JWT_SIGNING_KEY
          valueFrom:
            secretKeyRef:
              name: symmetric-keys
              key: jwt-signing-key
        readinessProbe: # Checks that the container is started
          httpGet:
            path: /api/mpestx/health/ready
            port: 80
          initialDelaySeconds: 8
          timeoutSeconds: 1
          periodSeconds: 20
          failureThreshold: 3
        livenessProbe: # Checks that the container is running
          httpGet:
            path: /api/mpestx/health/live
            port: 80
          initialDelaySeconds: 8
          timeoutSeconds: 1
          periodSeconds: 20
          failureThreshold: 3
        volumeMounts:
          - name: app-config
            mountPath: /app/configs/
            readOnly: true
          - name: mysql-credentials
            mountPath: /app/secrets/mysql/
            readOnly: true
          - name: redis-credentials
            mountPath: /app/secrets/redis/
            readOnly: true
      volumes:
      - name: app-config
        configMap:
          name: mpesapayment
      - name: mysql-credentials
        secret:
          secretName: mysql-credentials
      - name: redis-credentials
        secret:
          secretName: redis-credentials

---
apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "mpesapayment-hpa"
  namespace: crbt
  labels:
    app: "mpesapayment"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "mpesapayment"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      targetAverageUtilization: 80