serviceName: MPESA Payment API
httpPort: 9009
grpcPort: 9010
logLevel: -1
security:
  tlsCert: /Users/jessegitaka/Desktop/mpesapayments/certs/localhost/cert.pem
  tlsKey: /Users/jessegitaka/Desktop/mpesapayments/certs/localhost/key.pem
  serverName: localhost
  # insecure: true
databases:
- required: true
  type: sqlDatabase
  address: localhost:3306
  user: root
  password: hakty11
  schema: tracking-portal
  metadata:
    name: sqlWrites
    dialect: mysql
    orm: gorm
- required: true
  type: redisDatabase
  address: localhost:6379
  metadata:
    name: redisWrites